"""empty message

Revision ID: 66942934361d
Revises: a819850aaca9
Create Date: 2020-09-13 20:33:33.487843

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '66942934361d'
down_revision = 'a819850aaca9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('transactions_ibfk_2', 'transactions', type_='foreignkey')
    op.create_foreign_key(None, 'transactions', 'users', ['userId'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.create_foreign_key('transactions_ibfk_2', 'transactions', 'users', ['userId'], ['id'])
    # ### end Alembic commands ###