"""empty message
Revision ID: 88cfaa25072e
Revises: 
Create Date: 2020-08-15 20:31:52.237680
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '88cfaa25072e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('banks',
    sa.Column('bsb', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('bsb')
    )
    op.create_table('bankaccounts',
    sa.Column('accountNumber', sa.Integer(), nullable=False),
    sa.Column('bankId', sa.Integer(), nullable=True),
    sa.Column('accountName', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['bankId'], ['banks.bsb'], ),
    sa.PrimaryKeyConstraint('accountNumber')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=True),
    sa.Column('passwordHash', sa.String(length=255), nullable=True),
    sa.Column('registerDate', sa.DateTime(), nullable=True),
    sa.Column('bankAccountId', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['bankAccountId'], ['bankaccounts.accountNumber'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('bankaccounts')
    op.drop_table('banks')
    # ### end Alembic commands ###
