"""empty message

Revision ID: aa4c51d72d3f
Revises: 8d0d9d8e1682
Create Date: 2020-09-12 05:19:20.858029

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'aa4c51d72d3f'
down_revision = '8d0d9d8e1682'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('catagoryName', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_constraint('bankaccounts_ibfk_1', 'bankaccounts', type_='foreignkey')
    op.create_foreign_key(None, 'bankaccounts', 'banks', ['bankId'], ['bsb'], ondelete='CASCADE')
    op.drop_constraint('goals_ibfk_1', 'goals', type_='foreignkey')
    op.create_foreign_key(None, 'goals', 'users', ['userId'], ['id'], ondelete='CASCADE')
    op.drop_column('goals', 'description')
    op.drop_constraint('transactions_ibfk_1', 'transactions', type_='foreignkey')
    op.create_foreign_key(None, 'transactions', 'goals', ['goalId'], ['id'], ondelete='CASCADE')
    op.drop_constraint('users_ibfk_1', 'users', type_='foreignkey')
    op.create_foreign_key(None, 'users', 'bankaccounts', ['bankAccountId'], ['accountNumber'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.create_foreign_key('users_ibfk_1', 'users', 'bankaccounts', ['bankAccountId'], ['accountNumber'])
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.create_foreign_key('transactions_ibfk_1', 'transactions', 'goals', ['goalId'], ['id'])
    op.add_column('goals', sa.Column('description', mysql.VARCHAR(length=255), nullable=True))
    op.drop_constraint(None, 'goals', type_='foreignkey')
    op.create_foreign_key('goals_ibfk_1', 'goals', 'users', ['userId'], ['id'])
    op.drop_constraint(None, 'bankaccounts', type_='foreignkey')
    op.create_foreign_key('bankaccounts_ibfk_1', 'bankaccounts', 'banks', ['bankId'], ['bsb'])
    op.drop_table('category')
    # ### end Alembic commands ###